type = "card"
title = "AI 理论"
description = "记录一些 DeepSeek、Kimi 等公司发表论文的阅读笔记~"

[[items]]
title = "DeepSeek-OCR：通过2D光学映射压缩长上下文"
date = "2025/11/18"
content = "详细解析了 DeepSeek 开源的 OCR 模型如何利用视觉形态作为文本信息的压缩媒介，通过 2D 光学映射将长上下文压缩为少量视觉 token，从而大幅提升大语言模型处理长文本的效率"
link = "https://mp.weixin.qq.com/s/OX_GIaZ6jV-bxKF41vY_IQ"
image = "/wechat_images/deepseek.png"