type = "card"
title = "知识随记"
description = "记录一些零散的、即学即用的知识~"

[[items]]
title = "随机系统最优控制"
subtitle = "参考书目：《随机系统最优控制——理论及应用》方洋旺"
content = "主要整理了随机系统最优控制的一般理论、连续随机系统的随机最大值原理和离散随机系统的动态规划法"
link = "/wechat_official_account_collection/knowledge_notes_folder/stochastic_optimal_control"