type = "card"
title = "读书笔记"
description = "记录一些系统学习的知识~"

[[items]]
title = "Generative AI and Stochastic Thermodynamics -- A Tale of Free Energies"
date = "2026/09"
content = "生成式AI & 随机热力学 —— 自由能视角"
link = "/wechat_official_account_collection/reading_notes_folder/generative_ai_and_stochastic_thermodynamics"
image = "/wechat_images/generative_ai_and_stochastic_thermodynamics.png"