type = "card"
title = "随机系统最优控制"
description = "主要整理了随机系统最优控制的一般理论、连续随机系统的随机最大值原理和离散随机系统的动态规划法"


[[items]]
title = "离散随机控制系统的动态规划法"
#subtitle = "微信公众号"
content = "介绍了离散随机系统的最优控制动态规划法，分别针对完全状态信息和不完全信息情景，通过“逆时针递推求贝尔曼泛函关系、顺时针迭代求最优控制与状态估计”的流程求解，并附有统计线性化与准最优线性滤波等关键推导。"
link = "https://mp.weixin.qq.com/s/F3gvGM02MzbcXdq7hymd_g"

[[items]]
title = "概念、问题的标准化转换、庞特里亚金泛函"
#subtitle = "微信公众号"
content = "系统介绍了随机控制系统的基本模型、随机可控性判据、基于条件数学期望的最优准则、庞特里亚金最大值原理与贝尔曼动态规划等最优控制方法，以及通过扩大状态空间将时间最短、最优终端状态和能量最小控制统一转化为标准优化问题并借助庞特里亚金泛函求解的完整框架"
link = "https://mp.weixin.qq.com/s/b_TEtGsCeLAc_tynPLAOCg"
