type = "card"
title = "Generative AI and Stochastic Thermodynamics"
description = "生成式AI & 随机热力学 —— 自由能视角"

[[items]]
title = "Introduction & Mathematics Preliminaries"
#subtitle = "微信公众号"
date = "2026/10/8"
content = "揭示生成式AI与非平衡态随机热力学之间的深层联系。围绕“自由能”这一核心概念，阐述了ELBO、变分推断与物理中自由能变分推断的数学等价性，并说明扩散模型如何逆转热力学第二定律的加噪过程，从噪声中重建数据样本"
link = "https://mp.weixin.qq.com/s/1HJsAFjN3JhVyzV0c3OSBA"