type = "card"
title = "Generative AI and Stochastic Thermodynamics"
description = "生成式AI & 随机热力学 —— 自由能视角"

[[items]]
title = "离散随机控制系统的动态规划法"
#subtitle = "微信公众号"
date = "2026/10/8"
content = "介绍了离散随机系统的最优控制动态规划法，分别针对完全状态信息和不完全信息情景，通过“逆时针递推求贝尔曼泛函关系、顺时针迭代求最优控制与状态估计”的流程求解，并附有统计线性化与准最优线性滤波等关键推导。"
link = "https://mp.weixin.qq.com/s/1HJsAFjN3JhVyzV0c3OSBA"